### ISSUE TITLE
Biweekly for 2015-02-02

### ISSUE THREAD

**Issue by sckott** [ropensci-org/monthly#1]
@karthik include a line for the raltmetric update or let me know when at least release notes are done and I can add it - goes out 9 am on 2015-02-02, so before then

**Comment by karthik** [comment]
Sure thing, will do.

**Comment by karthik** [comment]
I added some comments and updates. If I finish a stable `rAltmetric` by Monday night, I'll add that in. Otherwise this looks great to go.

**Comment by sckott** [comment]
:+1:
