### ISSUE TITLE
pkgcheck updates

### ISSUE THREAD

**Issue by maelle** [ropensci-org/monthly#100]
@mpadge (maybe even a tech note, actually?)

**Comment by mpadge** [comment]
Another new check to announce, in action at https://github.com/ropensci-review-tools/pkgcheck/blob/main/tests/testthat/_snaps/pkgcheck/checks.md, which looks like this:

## Checks for [testpkgchecknotapkg (v0.0.0.9000)]()

git hash: [](/tree/)

- :heavy_check_mark: Package name is available
- :heavy_multiplication_x: does not have a 'codemeta.json' file.
- :heavy_multiplication_x: does not have a 'contributing' file.
- :heavy_multiplication_x: The following function has no documented return value: [test_fn]
- :heavy_check_mark: uses 'roxygen2'.
- :heavy_multiplication_x: 'DESCRIPTION' does not have a URL field.
- :heavy_multiplication_x: 'DESCRIPTION' does not have a BugReports field.
- :heavy_multiplication_x: Package has no HTML vignettes
- :heavy_multiplication_x: These functions do not have examples: [test_fn].
- :heavy_multiplication_x: Continuous integration checks unavailable (no URL in 'DESCRIPTION').
- :heavy_multiplication_x: Some statistical standards are missing
- :heavy_multiplication_x: This package still has TODO standards and can not be submitted
- :heavy_multiplication_x: Statistical standards should be documented in most package files, yet are mostly only documented in one file.

The last line is the new check. It fails whenever stats packages fail to move the "srrstats" tags to other locations throughout the package. Technically, it fails whenever > 50% of all standards statements remain within a single file, or whenever documentation is not in at least 2 sub-directories of package.
