### ISSUE TITLE
Remind that HTML is better for accessibility than PDF

### ISSUE THREAD

**Issue by maelle** [ropensci-org/monthly#106]
https://stat.ethz.ch/pipermail/r-package-devel/2022q2/007953.html

> Please consider the HTML alternative to any pdf, in any context, but especially in anything relating to R.

**Comment by llrs** [comment]
Just want to add/highlight that search.r-project.org works great and already available for all CRAN packages (and manuals) in html format (it is also mentioned on the  thread https://stat.ethz.ch/pipermail/r-package-devel/2022q2/007959.html)
