### ISSUE TITLE
new maintainer calls

### ISSUE THREAD

**Issue by maelle** [ropensci-org/monthly#125]
https://github.com/ropensci/charlatan/issues/123

**Comment by maelle** [comment]
https://github.com/ropensci/rgnparser/issues/14

**Comment by maelle** [comment]
https://github.com/ropensci/ritis/issues/23

**Comment by maelle** [comment]
https://github.com/ropensci/rredlist/issues/49

**Comment by maelle** [comment]
https://github.com/ropensci/wikitaxa/issues/20

**Comment by llrs** [comment]
Those are a lot of packages... Not sure if the monthly newsletter is automated according to the label but previous issues had the [label:"New Maintainer Wanted :wave:"](https://github.com/ropensci-org/monthly/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed+label%3A%22New+Maintainer+Wanted+%3Awave%3A%22)

**Comment by maelle** [comment]
oh right I forgot that :joy: here there are so many packages that it was faster this way anyway. This part isn't automated, it could become so. It isn't automated because we used to have very few calls.
