### ISSUE TITLE
RSS feed is broken

### ISSUE THREAD

**Issue by Bisaloo** [ropensci-org/monthly#13]
It was working up to a week (?) ago but now, zotero doesn't seem to be able to parse the link for each item and thunderbird doesn't even want to add the feed (validation fails).

[Link to the validation service](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fnews.ropensci.org%2Ffeed.xml).

**Comment by sckott** [comment]
thanks for the issue. 

that's weird as we've always had relative urls in the feed, the other issues i'm not sure about.  do you know of any tooling for helping make the feed valid?

I just tried it in my rss reader (Feedbin) and it worked fine.

**Comment by Bisaloo** [comment]
Interesting. I guess it's always been there then and a change in Zotero just revealed it now. I can try to pinpoint the exact cause for this.

No, I don't know any tool for that, sorry

**Comment by sckott** [comment]
okay, thanks

**Comment by maelle** [comment]
@Bisaloo we've now changed the feed link to https://ropensci.org/tags/newsletter/index.xml (or https://ropensci.org/tags/newsletter/index.json) so I'm going to close this. If you find any issue with the new feed please report it at https://github.com/ropensci/roweb3
