### ISSUE TITLE
Aug 14, 2019 feature use case idea

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/monthly#14]
#### Use case example
The Trafford Data Lab supports government decision-making in Trafford, Greater Manchester, UK. They shared use cases for [ropenaq](https://discuss.ropensci.org/t/promoting-r-and-ropensci-packages-in-uk-local-government/1776) to retrieve air quality information from the Manchester Piccadilly monitoring station, [fingertipsR](https://discuss.ropensci.org/t/using-fingertipsr-for-public-health-data-in-uk-local-government/1780) to access public health data on the rate of antidepressant prescribing, and [ghql](https://discuss.ropensci.org/t/querying-linked-data-to-improve-public-services/1781) to query linked data to map hot and cold spots of worklessness and improve public services.

Image: could use one of the use case images

Please don't use the Tiffany Timbers use case since it's a blog post Aug 27.

**Comment by sckott** [comment]
using this in todays nws
