### ISSUE TITLE
update on stat software review

### ISSUE THREAD

**Issue by maelle** [ropensci-org/monthly#148]

**Comment by mpadge** [comment]
@noamross This is reminder for us to provide an update in news-2023-04 on new stats editors and other stuff.

**Comment by maelle** [comment]
expected date of publication being April the 21st.

**Comment by maelle** [comment]
https://github.com/ropensci/roweb3/pull/537 (I opened it early because I needed to fix the code parsing posts since the blog became multilingual :zany_face: )

**Comment by maelle** [comment]
@mpadge @noamross friendly reminder! the newsletter will be published Friday next week, the 21st of April.
