### ISSUE TITLE
Depdenabot alerts

### ISSUE THREAD

**Issue by mpadge** [ropensci-org/monthly#149]
All credit for these ideas to @assignUser, and definitely not me. Depedenabot alerts are really easy to set up to monitor for updates to actions, like [this example](https://github.com/ropensci-review-tools/pkgcheck/blob/main/.github/dependabot.yml). Full GitHub [docs are here](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates).

@assignUser This is where we park ideas for our monthly newsletter. We'll ping you from the PR once that starts, and you can add the section if you want.

**Comment by maelle** [comment]
Header over to https://github.com/ropensci/roweb3/pull/537 :grin: I added a paragraph with the text above, feel free to suggest edits to it. Thank you!
