### ISSUE TITLE
Aug 14, 2019 in the news idea

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/monthly#15]
#### In the News?
(not sure where this fits, but nice to highlight. I retweeted it before)

[Being a better programmer and scientist with rOpenSci](https://mablab.org/post/ropensci/) is a very flattering
blog post by person who contributed to [refnet](https://github.com/ropensci/software-review/issues/256) with Auriel Fournier

**Comment by sckott** [comment]
using this in todays news
