### ISSUE TITLE
Cool experimental API packages

### ISSUE THREAD

**Issue by maelle** [ropensci-org/monthly#160]
cc @jonthegeek

https://jonthegeek.github.io/beekeeper/
https://jonthegeek.github.io/nectar/

**Comment by jonthegeek** [comment]
Ok, I've done the minimal cleanup that I wanted to do before your post: 
https://jonthegeek.github.io/beekeeper/
https://jonthegeek.github.io/nectar/

**Comment by maelle** [comment]
Thank you!!

**Comment by maelle** [comment]
Now added to the newsletter draft! I tagged you in the commit.
