### ISSUE TITLE
CRAN C/C++ again

### ISSUE THREAD

**Issue by maelle** [ropensci-org/monthly#163]
https://github.com/mpadge/settest by @mpadge

**Comment by mpadge** [comment]
Only slightly embarrassing thing is that it really is just C++17 enforcing pretty standard good C++ coding practices. The problem would never have arise if I had have been a better coder at the outset :grimacing: That said, the meta-purpose of that repo was to demonstrate/document how reducing difficult problems sometimes, in the R world, requires creating the simplest possible package containing the problem, and then messing with that until a solution can be found. It's a good reference for that general procedure.
