### ISSUE TITLE
Development tip: Check for partial matching as part of your testing & CI process

### ISSUE THREAD

**Issue by Bisaloo** [ropensci-org/monthly#165]
You can change your options to generate warnings on partial matching:

```r
options(
  warnPartialMatchAttr = TRUE,
  warnPartialMatchDollar = TRUE,
  warnPartialMatchArgs = TRUE 
)
```

But your options and Rprofile are ignored by R CMD check.

A way to still get warnings in your continuous integration is to integrate it to testthat by creating a special `setup-options.R` file, as in https://github.com/epiverse-trace/packagetemplate/pull/61. This file could also be used to change any other options (but use with caution to not create situations where it's too difficult to debug).

**Comment by maelle** [comment]
thank you!!
