### ISSUE TITLE
Aug 16, 2019 Lovelace stplanr in the news in Forbes mag!

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/monthly#17]
https://www.forbes.com/sites/carltonreid/2019/08/15/restrict-twice-as-deadly-suvs-in-u-k-cities-urge-transport-data-scientists/#429685c661e1

"Dr. Lovelace has put the raw crash data into R format, a type of software for statistical computing widely used by data scientists and statisticians"

Robin acknowledges rOpenSci in tweet https://twitter.com/robinlovelace/status/1162281092096770049

**Comment by sckott** [comment]
thanks. using this in todays news
