### ISSUE TITLE
Aug 19, 2019 promote help wanted issues

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/monthly#18]
Encourage rOpenSci package authors to help us help them get help on their package development. If they label an issue `help wanted` (no hyphen or emojis in label) then their issues can be found in a search of rOpenSci org: 
https://github.com/search?q=org%3Aropensci+label%3A"help+wanted"+state%3Aopen&type=Issues

or ropenscilabs org (where Ildi has specifically labelled some ropsec issues) https://github.com/search?q=org%3Aropenscilabs+label%3A%22help+wanted%22+state%3Aopen&type=Issues

Maybe authors could also post link to their `help wanted` issues in the forum https://discuss.ropensci.org/c/packages with tag `help wanted` and rOpenSci could tweet that link

**Comment by sckott** [comment]
sounds good to have an item on this. 

> Maybe authors could also post link to their help wanted issues in the forum

not sure i understand this. they'd just do a post with a link to their help wanted issues?

**Comment by stefaniebutland** [comment]
> they'd just do a post with a link to their help wanted issues?

Yes, that's what I was thinking. Is it cool or not cool for people to promote help wanted? (i.e. work for free). If cool, they could say "I'd like to add this new functionality...See `help wanted` issues" or "I'd like to improve docs ..."

**Comment by sckott** [comment]
yeah, makes sense, i think we should ask people to go into at least a bit of detail, more than just posting a link to the issues

**Comment by stefaniebutland** [comment]
100% agreed. The implicit intent here is to get more traffic in the forum by having people post a compelling blurb about what they want help on. Also contributes a sense of ongoing activity on community developed packages

**Comment by sckott** [comment]
nice
