### ISSUE TITLE
Updates to test-coverage r-lib action

### ISSUE THREAD

**Issue by rogerssam** [ropensci-org/monthly#216]
Codecov.io recently updated their API to apparently require an authentication token otherwise API requests fail due to rate limiting. This has been fixed in a recent update to the [r-lib actions test-coverage example](https://github.com/r-lib/actions/issues/822), but could do with some more publicity.

**Comment by maelle** [comment]
@rogerssam thanks so much for reporting this here, I really appreciate it!! I agree so much that I had already added it to the draft of the newsletter we'll send out tomorrow. https://github.com/ropensci/roweb3/pull/764/files#diff-dd9b8f384d4017b2103061398f02c38b69941a1f2999e83c07169b433934fe87R162 Thanks again!!
