### ISSUE TITLE
Oct 11, 2019 What do you want to know about testing? 

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/monthly#24]
One of our next Community Calls will be about testing (_Scott please add a phrase here if needed, like "testing in R package development"_). Tell us what you want to know about it or who you'd like to hear from by commenting in [our new Community Calls repository](https://github.com/ropensci-org/community-calls/issues/1).

**Comment by sckott** [comment]
fixed in 57014dfbf749aa6f146d776704696b9711639f86
