### ISSUE TITLE
allcontributors

### ISSUE THREAD

**Issue by maelle** [ropensci-org/monthly#250]
https://github.com/ropenscilabs/allcontributors @mpadge

**Comment by mpadge** [comment]
Plus make sure to link to https://allcontributors.org/ as source of that idea

**Comment by maelle** [comment]
will wait for your tech note so probably next month? :pleading_face:

**Comment by mpadge** [comment]
Thanksgiving has already happened for Canada, and US is end Nov, so yeah, I guess next month is better. That'll also give me time to get those recent fixes on to CRAN version.

**Comment by maelle** [comment]
@mpadge any update on a possible tech note? Any help needed?

**Comment by mpadge** [comment]
https://github.com/ropensci/roweb3/pull/888

**Comment by mpadge** [comment]
https://ropensci.org/blog/2024/11/26/allcontributors/ plus mentioned in upcoming Nov 24 news
