### ISSUE TITLE
refer to taking over maintenance chapter in biweekly

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/monthly#33]
In Call for Maintainers, good to refer to the maintenance chapter of dev guide

Instead of:
> Checkout our Contributing Guide for why and how to contribute to rOpenSci.

Maybe:
`Check out our guidance for [taking over maintenance of a package](https://devguide.ropensci.org/changing-maintainers.html).`

**Comment by sckott** [comment]
Good idea! thanks

**Comment by sckott** [comment]
done in 9ed2a153f160340b462a06e5965e2dc198abcb54
