### ISSUE TITLE
hugo

### ISSUE THREAD

**Issue by sckott** [ropensci-org/monthly#34]
@maelle trying to convert to hugo. see `to-hugo` branch.  I'm not sure how to replace jekyll's plugins in hugo, e.g., `{{ "RNeXML" | image_cran }}` and `{{ "RNeXML" | image_github }}` use https://github.com/ropensci/biweekly/blob/gh-pages/_plugins/image-link-cran.rb and https://github.com/ropensci/biweekly/blob/gh-pages/_plugins/image-link-github.rb respectively, to make png badges for cran and github. Not sure how to do that with hugo 

Also not sure what theme to used, just using harbor theme for now.

**Comment by maelle** [comment]
so it's "just" doing what `glue::glue()` would do in R, right? You need some sort of partial template and if you call it from _content_ (as opposed as from layouts files) then you need to create a shortcode that calls the partial.

**Comment by maelle** [comment]
I think that once a decision has been made regarding what should happen to the newsletter we could have a call to go through challenges?

**Comment by sckott** [comment]
not sure if glue is the right analogy. `image_cran` and `image_github` are Ruby functions that accept a character string, and output an png and link behind the png

Sounds good to wait

**Comment by maelle** [comment]
could you write an example input and output?

**Comment by sckott** [comment]
`{{ "RNeXML" | image_cran }}` would use the below function  - where `input` is "RNeXML" as an example

```ruby
def image_cran(input)
    x = input.to_s
    "<a target='_blank' href='https://cran.rstudio.com/web/packages/"+ x + "'><img src='../assets/img/octicon-package.png' width='25' style='border-radius: 6px 6px 6px 6px'></a>"
end
```

and output would be 

`<a target='_blank' href='https://cran.rstudio.com/web/packages/RNeXML'><img src='../assets/img/octicon-package.png' width='25' style='border-radius: 6px 6px 6px 6px'></a>`

**Comment by maelle** [comment]
In Hugo you can do something like 

```
<a target='_blank' href='https://cran.rstudio.com/web/packages/{{ .pkgname }}'><img src='../assets/img/octicon-package.png' width='25' style='border-radius: 6px 6px 6px 6px'></a>
```

if the thing needs to be created in the content, then you'd define a shortcode. https://gohugo.io/content-management/shortcodes/

Not sure if it helps?

**Comment by sckott** [comment]
thanks - i'll try it soon

**Comment by maelle** [comment]
Good, I can help when you do that

**Comment by sckott** [comment]
tried for a bit, but couldn't figure out the structure of how a hugo directory needs to be,
