### ISSUE TITLE
what can be personalized in Mailchimp?

### ISSUE THREAD

**Issue by maelle** [ropensci-org/monthly#37]
Could the screen below feature rOpenSci logo for instance?

![image](https://user-images.githubusercontent.com/8360597/90502230-c742da00-e14d-11ea-9ce5-f54e4f3d852b.png)

**Comment by sckott** [comment]
good question. 

it has the logo now 

![Screen Shot 2020-08-18 at 2 41 52 PM](https://user-images.githubusercontent.com/577668/90568565-00387a00-e161-11ea-8485-e7e071d082c9.png)

anything else you think should be added?

**Comment by maelle** [comment]
That's probably enough, thank you!

Maybe there could be less occurrences of subscription/subscribing by the way, and also maybe a link to the newsletter archive / the website. (or does continue to our website link to rOpenSci website? probably?)

**Comment by sckott** [comment]
good idea, less "subscription"

no, I don't think it continues to the newsletter site or our site. will add a link to the newsletter

**Comment by sckott** [comment]
![Screen Shot 2020-08-19 at 8 07 28 AM](https://user-images.githubusercontent.com/577668/90652577-0f680800-e1f3-11ea-9c93-24fbaa0182f8.png)

**Comment by maelle** [comment]
Yay! Maybe add "past issues of" 🙂, and thank you before that?

**Comment by sckott** [comment]
![Screen Shot 2020-08-21 at 8 55 21 AM](https://user-images.githubusercontent.com/577668/90910401-1aa26b80-e38c-11ea-9879-f06dc051abeb.png)


good?

**Comment by maelle** [comment]
yes! :smile_cat:
