### ISSUE TITLE
make cmd to prep (at least in part) 2months/2min

### ISSUE THREAD

**Issue by sckott** [ropensci-org/monthly#39]
@stefaniebutland

**Comment by sckott** [comment]
@stefaniebutland @steffilazerte

started working on automating 2 months 2 minutes https://github.com/ropensci/biweekly/blob/gh-pages/scripts/two_months_two_minutes.R 

however, its not easy. The newsletters have a html feed but the content is not easily parsable. In the 2 months posts theres lots of different information pulled together that can be automated but just takes some time to code up.

**Comment by stefaniebutland** [comment]
Thanks for starting Scott!!

**Comment by stefaniebutland** [comment]
After manually doing a 2months 2 mins post last night, I'm thinking maybe we can ask Steffi (later) to help with this. We can harmonize some parts of the post more with the newsletter to make it more easily automated.

**Comment by sckott** [comment]
Sounds good
