### ISSUE TITLE
Aug 24, 2020 Contributing Guide release

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/monthly#40]
https://contributing.ropensci.org/

The purpose of the guide is to welcome you to rOpenSci and help you recognize yourself as a potential contributor. It will help you figure out what you might gain by giving your time, expertise, and experience; match your needs with things that will help rOpenSci’s mission; and connect you with resources to help you along the way. Is there something you might like to contribute that isn’t addressed there? Open an issue in the [GitHub repository for the Guide](https://github.com/ropensci-org/contributing-guidance).

**Comment by sckott** [comment]
I assume we put this in the __ropensci HQ__ section at the top ?

**Comment by stefaniebutland** [comment]
yes pls

**Comment by sckott** [comment]
used in todays news
