### ISSUE TITLE
Interview with Anna

### ISSUE THREAD

**Issue by maelle** [ropensci-org/monthly#41]
For the next newsletter issue: Awesome podcast episode starring @annakrystalli http://us-rse.org/rse-stories/2020/anna-krystalli/ where she among other exciting things mentions rOpenSci and Software Peer Review in particular.

**Comment by sckott** [comment]
perfect, thanks!

**Comment by sckott** [comment]
done in a720a243360db89bf71e263aabf43c71a660277c
