### ISSUE TITLE
Nov 8, 2020 save the date - community call Wed Dec 16

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/monthly#43]
https://twitter.com/rOpenSci/status/1324820331580698624

announcement on website not ready till ~Nov 16

**Comment by sckott** [comment]
thanks!

**Comment by stefaniebutland** [comment]
https://ropensci.org/commcalls/dec2020-datarepos/

Our next Community Call - The Wild World of Data Repositories is Wednesday, December 16, 10-11 am Pacific / 18:00 UTC.

Rather than detailing general concepts, we'll get quickly into challenges in data deposition & reuse, and vision for new tools as a call to action.
Details & add to your calendar: https://ropensci.org/commcalls/dec2020-datarepos/

**Comment by sckott** [comment]
thanks

**Comment by sckott** [comment]
done
