### ISSUE TITLE
Add Twitter card metadata

### ISSUE THREAD

**Issue by maelle** [ropensci-org/monthly#6]
@sckott I'm happy to help with this! 😺

**Comment by sckott** [comment]
what needs to be done?

**Comment by maelle** [comment]
Adding metadata to https://github.com/ropensci/biweekly/blob/gh-pages/_includes/head.html

See my issue or PR at roweb2 for links to guidance https://github.com/ropensci/roweb2/issues/290

**Comment by maelle** [comment]
And see https://github.com/maelle/roweb2/blob/8b6341c5a3aea30d81d57b2f5adadff3e3d071ab/themes/ropensci/layouts/partials/head.html

Instead of Hugo variables there are probably things you can hardcode.

In the PR I had put a link to Twitter card validator, very useful

**Comment by sckott** [comment]
thanks

**Comment by maelle** [comment]
but now it was solved my my PR
