### ISSUE TITLE
labelathon summary + next ones planned?

### ISSUE THREAD

**Issue by maelle** [ropensci-org/monthly#64]
cc @stefaniebutland I'll need a short blurb for the next newsletter (planned for Friday, May the 14th). :pray:

**Comment by maelle** [comment]
friendly ping @stefaniebutland :smile_cat: (newsletter planned for Friday, May the 21th so ideally I'd need the blurb by Tuesday)

**Comment by stefaniebutland** [comment]
@steffilazerte please and thanks

**Comment by steffilazerte** [comment]
Eeep, sorry! I forgot, but now I'm on it 😅

**Comment by steffilazerte** [comment]
I hope I didn't delay the newsletter on this, but if it's not until next week, I'll update this blurb tomorrow or early next week once we have the details from tonight's label-athon. But here's the draft (@stefaniebutland is this in line with what you wanted/expected?)

---
We held our first two Social Co-Working and Label-athon events on April 29th and May 13th. These were truly international events with 14 participants from Canada, Germany, Switzerland, USA, the UK, France, Singapore, and Mexico. We had a blast socializing (scavenger hunts!) and co-working on our personal R projects including repository organization, creating/labelling issues, preliminary research, personal GitHub README files, and those packages you can never find time for. We had quiet and noisy rooms to work in, so everyone was able to find an environment that worked best for them.

Sound like fun? We have two more coming up! 
- [Thurs May 27th 9am Pacific](https://ropensci.org/events/labelathon03/) (16:00 UTC) - [Registration encouraged!](https://form.jotform.com/211236537172249)
- [Thurs June 10th 5pm Pacific](https://ropensci.org/events/labelathon04/) (Fri June 11th 00:00 UTC) - [Registration encouraged!](https://form.jotform.com/211236201763243)

**Comment by steffilazerte** [comment]
Okay, updated to include last nights data! I think it's ready to go. @stefaniebutland Edit as you like!

**Comment by maelle** [comment]
used the text in my newsletter PR, thank you!!
