### ISSUE TITLE
newsletter display SendGrid

### ISSUE THREAD

**Issue by maelle** [ropensci-org/monthly#70]
https://twitter.com/Lluis_Revilla/status/1407658812899799041

h/t @llrs

**Comment by maelle** [comment]
Issue encountered by @stefaniebutland too https://twitter.com/StefanieButland/status/1407756490111209473

**Comment by maelle** [comment]
@stefaniebutland and I tested another font, Arial, and I've made a note to use it next time (in the newsletter checklist https://github.com/ropensci/roweb3#newsletter). Thanks both for the report!

**Comment by llrs** [comment]
Fixed! 
![Screenshot from 2021-08-31 09-38-13](https://user-images.githubusercontent.com/6818218/131462503-21e9f35f-c509-4d67-b5ea-8b39c17d96ef.png)

Now it is looking great!
