### ISSUE TITLE
Mention birds talks in the August newsletter

### ISSUE THREAD

**Issue by maelle** [ropensci-org/monthly#72]
by @mpadge and @steffilazerte.

At least links to slides, preferably also recordings.

**Comment by steffilazerte** [comment]
Sure, when do you need this by?

**Comment by maelle** [comment]
In one month, as if I followed correctly the talks won't be public by next Friday (July newsletter).

However one thing that could be done before the July newsletter is updating the website events page?

**Comment by steffilazerte** [comment]
No I don't think they'll be public until after the conference (if then), but Mark and I might have them publicly available on our personal sites before then (but I probably won't be ready by next Friday :D). 

I'll talk to Stef about the events page and add them.

**Comment by maelle** [comment]
> No I don't think they'll be public until after the conference (if then), but Mark and I might have them publicly available on our personal sites before then (but I probably won't be ready by next Friday :D).

Good! :ok_hand:

**Comment by maelle** [comment]
@steffilazerte @mpadge should the blurb about your talks & their recordings be in the next newsletter (next week) or in the September one? If your choice is the next newsletter I'd need the blurb by the end of this week, and it'd be nice to also list the talks https://ropensci.org/talks/ (via https://github.com/ropensci/roweb3/blob/master/content/events/2021-08-10-aos-sco2021.md cf https://github.com/ropensci/roweb3#events)

**Comment by steffilazerte** [comment]
I can provide a blurb and link to my slides and recording. I know how to add an event, but I'm not clear how to add a talk. Do they get automagically added if talk metadata is added to the event? 

Also, does it matter that while I mention rOpenSci in my talk, my talk is not about nor for rOpenSci?

**Comment by maelle** [comment]
> Do they get automagically added if talk metadata is added to the event?

Yes! If you do that in a separate PR I can help.

> Also, does it matter that while I mention rOpenSci in my talk, my talk is not about nor for rOpenSci?

Right, always tricky! I'd still include it but feel free to ask for other opinions (including your own choice of course!) :thinking:

**Comment by mpadge** [comment]
Both @steffilazerte's and my talk were very strongly focussed on rOpenSci packages, so I definitely think this is worth mentioning, because it's staff giving publicity to other people's packages, which is part of our job, I'd say.

**Comment by maelle** [comment]
If @steffilazerte agrees I'll be waiting for the blurb then :grin:

**Comment by steffilazerte** [comment]
@mpadge do you have a link to your talk recording online somewhere? II see that you have the slides [here](https://github.com/mpadge/presentations/tree/main/2021/aos21).

**Comment by steffilazerte** [comment]
If you don't, and you don't mind, I can host it on my site, so we can link to it (also I try to get links to as many of the talks as possible after a symposium!)
