### ISSUE TITLE
how to use memoise in packages

### ISSUE THREAD

**Issue by maelle** [ropensci-org/monthly#74]
build time vs run time dep

**Comment by maelle** [comment]
From @mpadge

> in <mypkg>.R put `@importFrom memoise memoise.

**Comment by mpadge** [comment]
[Here's an rOpenSci example](https://github.com/ropensci/mapscanner/blob/2a4097e0d0c105bdf1c51ffecc1b1ec8ce58e4a0/R/mapscanner-package.R#L1-L6) of the relatively few packages which do need that trick to access the namespace without using any of the functions. Plus an [example of how it is actually used in that package](https://github.com/ropensci/mapscanner/blob/2a4097e0d0c105bdf1c51ffecc1b1ec8ce58e4a0/R/rectify-maps.R#L163-L164), if that helps. I prefix `memoise`d versions with `m_`, which i find makes a useful distinction.

**Comment by maelle** [comment]
Thank you! That's nifty :grin:

**Comment by alexpghayes** [comment]
Is the idea that this way you don't need a `memoise` in Suggests?

**Comment by maelle** [comment]
You still do but you'd avoid the NOTE

```
Result: NOTE
    Namespace in Imports field not imported from: ‘memoise’
     All declared Imports should be used. 
```

**Comment by maelle** [comment]
(note that this is not specific to memoise cf message by @jimhester in the Slack)
