### ISSUE TITLE
Post about the newsletter in December 2020

### ISSUE THREAD

**Issue by maelle** [ropensci-org/monthly#8]
Looking at old tweets I saw that the newsletter was created in December so it will be 4 years old in December.

What about writing a tech note about it? Why you created it, and since it is Markdown, a small analysis using `commonmark`+`xml2`+`tidytext` to look at section titles over time, length, most frequent URLs domains...

**Comment by maelle** [comment]
Then the following newsletter would feature a link to a tech note about the newsletter! 😮

**Comment by sckott** [comment]
yay 4 years!  sounds good!

**Comment by stefaniebutland** [comment]
maybe even better for 5yrs now that Scott is automating parts of it!!

**Comment by sckott** [comment]
good idea stef. ill put a reminder so i don't forget

**Comment by sckott** [comment]
not going to do this
