### ISSUE TITLE
community call Dec 7

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci-org/monthly#85]
### Community call. @ropensci-review-bot help!

Tuesday, 07 December 2021 17:00 UTC we'll share how we are [**Enhancing Software Peer Review with GitHub Automation**](/commcalls/dec2021-automation/).

Speakers Arfon Smith, Karthik Ram, Maëlle Salmon, and Noam Ross will discuss how rOpenSci has worked with [The Journal of Open Source Software (JOSS)](https://joss.theoj.org/) to extend their approach of [chatops-driven publishing](https://www.arfon.org/chatops-driven-publishing) into a new GitHub chat-bot that manages our editorial process: assigning tasks, tagging issues, running tests on software submissions, and returning reports to reviewers and editors, all from the comfort of a GitHub issue comment. Chat-ops automation has been critical to JOSS’s success, and shows huge promise for automating even more tedious tasks like frequent software checks and compliance with best practices. We will show how our new review bot improves the author and editor experience, **demonstrate how other teams can use and customize the bot**, and discuss how this approach can be extended to tackle other automation, code review, and reproducibility challenges.

Lots of time for Q & A during the session.

Follow the [community call page link](/commcalls/dec2021-automation/) for practical information. 
**Everyone is welcome, no RSVP needed!**

**Comment by maelle** [comment]
Thanks for the text @stefaniebutland
